# Generated by Django 2.0.6 on 2020-11-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='course',
            new_name='courses',
        ),
    ]
