# Generated by Django 2.0.6 on 2020-11-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201110_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='courses',
            new_name='course',
        ),
    ]
